### ISSUE TITLE
[Suggestion] If and else

### ISSUE THREAD

**Issue by supercam19** [MysteryBlokHed/databind#83]
An if/else statement:

# Example:
```
func condition
tag load
    var i := 10
    if tvar i matches ..9
        say var i is less than 9
        var i = 10
        say switched var i to 10!
    else
        say var i is 10 or above
        var i = 10
        say switched var i to 10!
    end
end
```

This would be compiled similar to a while loop, creating functions to run the if, or else.

# Compiled:
function example:condition
```
execute if score example matches ..9 run function example:if_abcd
execute unless score exaple matches ..9 run function example:else_abcd
```

function example:if_abcd:
```
say var i is less than 9
scoreboard players set example i 10
say switched var i to 10!
```

function example:unless_abcd:
```
say var i is 10 or above
scoreboard players set example i 10
say switched var i to 10!
```

**Comment by MysteryBlokHed** [comment]
One problem that could happen is the `if` block modifying the variable that was tested, eg. if the test was `tvar example matches 10` and the if statement changes it to a different value. This would cause both the `if` and `else` blocks' code to be run.

A potential solution could be either to create a variable per statement to store the result of the test, or to have one objective with multiple "players" that store the result of each if statement.

Something like this:

```mcfunction
# only run for the first if statement created
scoreboard objectives add if_results_abcd

# for each if statement
execute if score example matches ..9 run scoreboard players set --databind-abcd if_results_abcd 1
execute unless score example matches ..9 run scoreboard players set --databind-abcd if_results_abcd 0
```

Could prevent both blocks from being run.
I'll open a PR to do this when I get a chance.
